import os
from pathlib import Path

from github import Github

from .models import BmlResult, RunMetadata


def _repo():
    g = Github(os.environ["GITHUB_TOKEN"])
    repo_name = os.environ["GITHUB_REPOSITORY"]
    return g.get_repo(repo_name)


def open_results_pr(result: BmlResult) -> str:
    """Commits updated pull.csv + opens a PR summarising the BML run. Returns PR URL."""
    repo = _repo()
    run = result.run
    branch = f"bml/{run.run_id}"
    base = repo.default_branch

    # Get base SHA
    base_sha = repo.get_branch(base).commit.sha
    repo.create_git_ref(ref=f"refs/heads/{branch}", sha=base_sha)

    # Commit pull.csv update
    pull_csv_path = "pull.csv"
    current = repo.get_contents(pull_csv_path, ref=base)
    new_content = Path(pull_csv_path).read_text()
    repo.update_file(
        path=pull_csv_path,
        message=f"bml({run.run_id}): update PULL hypotheses (score={result.pull_score})",
        content=new_content,
        sha=current.sha,
        branch=branch,
    )

    # Commit runs.json update
    runs_path = ".bml/runs.json"
    runs_content = Path(runs_path).read_text()
    try:
        current_runs = repo.get_contents(runs_path, ref=base)
        repo.update_file(
            path=runs_path,
            message=f"bml({run.run_id}): mark run measured",
            content=runs_content,
            sha=current_runs.sha,
            branch=branch,
        )
    except Exception:
        repo.create_file(
            path=runs_path,
            message=f"bml({run.run_id}): initialise run store",
            content=runs_content,
            branch=branch,
        )

    hyp = result.updated_hypothesis
    m = run.metrics
    ctr = f"{m.clicks / m.impressions:.2%}" if m and m.impressions else "—"
    warning_section = f"\n> ⚠️ **Local minima risk:** {result.local_minima_warning}\n" if result.local_minima_warning else ""

    pr_body = f"""## BML Run `{run.run_id}`

**Variable tested:** `{run.active_variable}`
**PULL Score:** {result.pull_score} / 5
{warning_section}
### Ad Metrics

| Metric | Value |
|--------|-------|
| Impressions | {m.impressions if m else "—"} |
| Clicks | {m.clicks if m else "—"} |
| CTR | {ctr} |
| Avg CPC | {"${:.2f}".format(m.average_cpc_usd) if m else "—"} |
| Conversion Rate | {"{:.1%}".format(m.conversion_rate) if m else "—"} |
| Deploy URL | {run.deploy_url or "—"} |

### Updated PULL Hypotheses

| Variable | Value |
|----------|-------|
| project | {hyp.project} |
| urgency | {hyp.urgency} |
| look | {hyp.look} |
| lacking | {hyp.lacking} |

_Generated by [auto-bml](https://github.com/beakerstreet/auto-bml)_
"""

    pr = repo.create_pull(
        title=f"BML run {run.run_id} — {run.active_variable} — score {result.pull_score}/5",
        body=pr_body,
        head=branch,
        base=base,
    )
    return pr.html_url
